export const contactsData = [
    { name: "Prof. Basanta Pradhan", phone: "501 / 201", email: "director", department: "Director" },
    { name: "Bharti Nandwani", phone: "554 / 254", email: "bharti", department: "Faculty" },
    { name: "Chandrasekhar S.", phone: "551 / 251", email: "chandra", department: "Faculty" },
    { name: "Disha Gupta", phone: "553 / 253", email: "disha", department: "Faculty" },
    { name: "Ganesh Kumar", phone: "522", email: "agk", department: "Faculty" },
    { name: "Gopakumar Achathankutty", phone: "552 /252", email: "gopakumar", department: "Faculty" },
    { name: "Manisha Jain", phone: "517", email: "manishajain", department: "Faculty" },
    { name: "Rajendra Vaidya", phone: "514", email: "vaidya", department: "Faculty" },
    { name: "Rajeswari Sengupta", phone: "555 / 255", email: "rajeswari", department: "Faculty" },
    { name: "Rupayan Pal", phone: "545", email: "rupayan", department: "Faculty" },
    { name: "Sargam Gupta", phone: "544 / 244", email: "sargam", department: "Faculty" },
    { name: "Shubhro Sarkar", phone: "543 / 243", email: "shubhro", department: "Faculty" },
    { name: "Sudhakar Yedla", phone: "533 / 233", email: "sudhakar", department: "Faculty" },
    { name: "Swati Sharma", phone: "523 /246", email: "swati", department: "Faculty" },
    { name: "Taniya Ghosh", phone: "536 / 236", email: "taniya", department: "Faculty" },
    { name: "Vijayalaxmi Pandey", phone: "503", email: "vijay", department: "Faculty" },
    { name: "Ashima Goyal", phone: "512", email: "ashima", department: "Faculty" },
    { name: "Nachane D.M.", phone: "534", email: "nachane", department: "Faculty" },
    { name: "Amit Gaikwad", phone: "507", email: "amitg", department: "Estate & Maintenance" },
    { name: "Archana Sharma", phone: "542", email: "archana", department: "Administration & HR" },
    { name: "Fabina D'mello", phone: "576", email: "fabina", department: "Student Office" },
    { name: "Gawde Narayan", phone: "569", email: "gawde", department: "Accounts" },
    { name: "Jai Mohan Pandit", phone: "505 / 205", email: "jmpandit", department: "Registrar" },
    { name: "Lavina D'Souza", phone: "539", email: "lavina", department: "Registar's Office" },
    { name: "Lingaraj Panda", phone: "548 / 248", email: "lingaraj", department: "I.T. Department" },
    { name: "Mahesh Kumar", phone: "571", email: "mahesh", department: "Accounts" },
    { name: "Martha Lobo", phone: "585", email: "martha", department: "Director's Office" },
    { name: "Mukund Bhambere", phone: "538 / 238", email: "mukund", department: "Accounts" },
    { name: "Nelson D'souza", phone: "560", email: "nelson", department: "Estate & Maintenance" },
    { name: "Pratiksha Worlikar", phone: "530", email: "pratiksha", department: "Student Office" },
    { name: "Pravin Dalvi", phone: "580", email: "pravind", department: "I.T. Department" },
    { name: "S. M. Pujar", phone: "528 / 228", email: "pujar", department: "Library" },
    { name: "Ranjana Jha", phone: "584 / 265", email: "ranjana", department: "Accounts" },
    { name: "Samir Parab", phone: "588 / 288", email: "samir", department: "Administration & HR" },
    { name: "Sayli Charatkar", phone: "530", email: "sayli", department: "Administration & HR" },
    { name: "Vinita Hattangadi", phone: "504", email: "vinita", department: "Library" },
    { name: "Vishakha Narvekar", phone: "578", email: "vishakha", department: "Accounts" },
  { "name": "A.C. Plant", "phone": "568", "department": "Sites" },
  { "name": "Admin Conference Room", "phone": "204", "department": "Sites" },
  { "name": "Cafeteria", "phone": "599", "department": "Sites" },
  { "name": "CCTV Operator", "phone": "300", "department": "Sites" },
  { "name": "Driver’s Room", "phone": "309", "department": "Sites" },
  { "name": "Doctor's Room", "phone": "594", "department": "Sites" },
  { "name": "Dining Hall (Guest House)", "phone": "412", "department": "Sites" },
  { "name": "Faculty Lounge", "phone": "540", "department": "Sites" },
  { "name": "Guest House Visitor’s Lounge", "phone": "411", "department": "Sites" },
  { "name": "Guest House Reception", "phone": "401", "department": "Sites" },
  { "name": "Helpdesk - CC", "phone": "581 / 583", "department": "Sites" },
  { "name": "Lift - near Canteen", "phone": "574", "department": "Sites" },
  { "name": "Lift - Library", "phone": "575", "department": "Sites" },
  { "name": "Library", "phone": "528 / 228", "department": "Sites" },
  { "name": "Gym", "phone": "242", "department": "Sites" },
  { "name": "New Hostel Incharge", "phone": "596", "department": "Sites" },
  { "name": "New Hostel Main Gate", "phone": "3300", "department": "Sites" },
  { "name": "New Hostel Housekeeping", "phone": "3310", "department": "Sites" },
  { "name": "New Hostel Lift (North Side)", "phone": "475", "department": "Sites" },
  { "name": "New Hostel Lift (South Side)", "phone": "476", "department": "Sites" },
  { "name": "New Recreation (Gr & 1st Floor)", "phone": "477", "department": "Sites" },
  { "name": "Research Block-1 Lift", "phone": "472", "department": "Sites" },
  { "name": "Research Block-2 Lift", "phone": "473", "department": "Sites" },
  { "name": "Research Block-3 Lift", "phone": "474", "department": "Sites" },
  { "name": "Seanza Hall", "phone": "209", "department": "Sites" },
  { "name": "Security (Main Gate)", "phone": "301 / 302", "department": "Sites" },
  { "name": "Seminar Halls", "phone": "567", "department": "Sites" },
  { "name": "Swimming Pool", "phone": "220", "department": "Sites" },
  { "name": "Tel. Operator / Reception", "phone": "9 / 564", "department": "Sites" },
  { "name": "Office Boy at Admin Ground Floor", "phone": "303", "department": "Sites" },
  { "name": "Office Boy at Admin First Floor", "phone": "304", "department": "Sites" },
  { "name": "Office Boy at Accounts", "phone": "305", "department": "Sites" },
  { "name": "Dindoshi (W)", "phone": "28712869", "department": "Emergency" },
  { "name": "Dindoshi (E)", "phone": "28406729", "department": "Emergency" },
  { "name": "Fire Brigade", "phone": "28770781", "department": "Emergency" },
  { "name": "Police Station (Dindoshi)", "phone": "28770781", "department": "Emergency" },
  { "name": "IQAC Office", "phone": "323", "department": "Emergency" },
  { "name": "Placement Committee", "phone": "558", "department": "Emergency" },
  { "name": "MFEME Office", "phone": "527", "department": "Emergency" }
];
